// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxkkiecaitspefrxjfpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a2tpZWNhaXRzcGVmcnhqZnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzM0MTMsImV4cCI6MjA2MjA0OTQxM30.Mwdq9Tjcbc_pZlgmmzGvVz0P9tL8JXs8sLMgAuVujlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);